"""Desktop launcher for the dashboard — double-click, no AI, no terminal ceremony.

`recall shortcut` puts a launcher with the recall mark onto the user's Desktop
that starts `recall dashboard` for THIS project. Per OS family:

  Windows   "recall dashboard - <name>.lnk" with the brand .ico; the actual
            runner is a .bat tucked into the project's .mind/ (the console
            window doubles as the log, `pause` keeps errors readable)
  macOS     recall-dashboard-<name>.command  (Finder opens it in Terminal)
  Linux     recall-dashboard-<name>.desktop  (Terminal=true, Icon= the brand png)

The interpreter is pinned to sys.executable at creation time so the launcher
works even when `recall` is not on the double-click PATH. Moved your venv?
Run `recall shortcut` again — it overwrites in place.
"""

from __future__ import annotations

import os
import re
import stat
import subprocess
import sys
from pathlib import Path

ASSETS = Path(__file__).parent / "assets"


def desktop_dir() -> Path:
    """The real Desktop folder — on Windows via the registry (OneDrive moves it)."""
    if sys.platform == "win32":
        try:
            import winreg

            key = r"Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders"
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key) as k:
                raw, _ = winreg.QueryValueEx(k, "Desktop")
            p = Path(os.path.expandvars(raw))
            if p.is_dir():
                return p
        except OSError:
            pass
        return Path(os.environ.get("USERPROFILE", str(Path.home()))) / "Desktop"
    d = Path.home() / "Desktop"
    return d if d.is_dir() else Path.home()


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-")
    return s or "project"


def launcher_spec(repo: Path, port: int, py: str, platform: str | None = None) -> tuple[str, str]:
    """(filename, content) for the runner script — pure, so every OS variant is testable.

    On Windows the returned .bat is the ENGINE behind the Desktop .lnk (which
    carries the icon); on macOS/Linux the returned file IS the Desktop launcher.
    """
    platform = platform or sys.platform
    name = _slug(repo.name)
    if platform == "win32":
        return (
            f"recall-dashboard-{name}.bat",
            "@echo off\r\n"
            "rem generated by `recall shortcut` — the Desktop link points here\r\n"
            f"title recall dashboard - {name}\r\n"
            f'cd /d "{repo}"\r\n'
            f'"{py}" -m recall.cli dashboard --port {port}\r\n'
            "pause\r\n",
        )
    if platform == "darwin":
        return (
            f"recall-dashboard-{name}.command",
            "#!/bin/sh\n"
            "# generated by `recall shortcut` — double-click to start the dashboard\n"
            f'cd "{repo}" || exit 1\n'
            f'exec "{py}" -m recall.cli dashboard --port {port}\n',
        )
    icon = ASSETS / "recall.png"
    icon_line = f"Icon={icon}\n" if icon.exists() else ""
    return (
        f"recall-dashboard-{name}.desktop",
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name=recall dashboard — {name}\n"
        f"Comment=Project memory dashboard for {repo}\n"
        f'Exec="{py}" -m recall.cli dashboard --port {port} --repo "{repo}"\n'
        f"Path={repo}\n"
        f"{icon_line}"
        "Terminal=true\n",
    )


def _ps_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _write_lnk(lnk: Path, target: Path, workdir: Path, icon: Path | None) -> None:
    """Create a Windows .lnk via the shell COM object — the only way to get an icon."""
    lines = [
        f"$s = (New-Object -ComObject WScript.Shell).CreateShortcut({_ps_quote(str(lnk))})",
        f"$s.TargetPath = {_ps_quote(str(target))}",
        f"$s.WorkingDirectory = {_ps_quote(str(workdir))}",
        "$s.Description = 'recall dashboard — project memory, no AI needed'",
    ]
    if icon and icon.exists():
        lines.append(f"$s.IconLocation = {_ps_quote(str(icon) + ',0')}")
    lines.append("$s.Save()")
    subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command", "; ".join(lines)],
        check=True, capture_output=True,
    )


def create_shortcut(repo: Path, port: int = 7099, desktop: Path | None = None) -> Path:
    """Write the launcher onto the Desktop and return its path. Overwrites in place."""
    desktop = desktop or desktop_dir()
    desktop.mkdir(parents=True, exist_ok=True)
    filename, content = launcher_spec(repo, port, sys.executable)
    if sys.platform == "win32":
        # engine .bat lives out of sight in .mind/; the Desktop gets a .lnk
        # with the brand icon (a bare .bat can't carry one)
        mind = repo / ".mind"
        mind.mkdir(exist_ok=True)
        bat = mind / "dashboard-launcher.bat"
        bat.write_text(content, encoding="utf-8", newline="")
        legacy = desktop / filename
        if legacy.exists():  # pre-icon versions dropped the bare .bat here
            legacy.unlink()
        lnk = desktop / f"recall dashboard - {_slug(repo.name)}.lnk"
        _write_lnk(lnk, bat, repo, ASSETS / "recall.ico")
        return lnk
    path = desktop / filename
    path.write_text(content, encoding="utf-8", newline="")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def remove_shortcut(repo: Path, desktop: Path | None = None) -> bool:
    """Delete the launcher (and the Windows engine .bat) if present."""
    desktop = desktop or desktop_dir()
    filename, _ = launcher_spec(repo, 0, "x")
    removed = False
    for p in (
        desktop / filename,
        desktop / f"recall dashboard - {_slug(repo.name)}.lnk",
        repo / ".mind" / "dashboard-launcher.bat",
    ):
        if p.exists():
            p.unlink()
            removed = True
    return removed
